# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: false
language: python
python:
    - 2.7
    - 3.3
    - 3.4
install:
    - pip install -r requirements_dev.txt
script:
    - make lint
    - make test-coverage
    - make docs
    - make dist
    - make dist-clean
after_success:
    coveralls
